### ISSUE TITLE
Will not load on Window 10 pro

### ISSUE THREAD

**Issue by jhmblvd** [vtorrent/vTorrent-Client#11]
When trying to run I get this error "this application failed to start because it could not fin or load the QT platform plugin 'windows' Reinstalling may fix the problem.
Need to change my 2FA and cannot move forward with new phone until this is fixed

**Comment by vtorrent** [comment]
Dear jhmblvd,

Thank you for your feedback.

Windows 10 v1803 compatibility have been added to the release page

(vTorrent_RC4_0821-Win_1803.zip)

Regards,
vTorrent
