### ISSUE TITLE
Cannot get wallet to sync

### ISSUE THREAD

**Issue by jhmblvd** [vtorrent/vTorrent-Client#13]
Here I am again, moved wallet to new computer, downloaded the newest version 5.7 connected the nodes, been over a week and my balance is still not showing and I'm still not synced. My phone crashed along with my 2FA, I now have the blockchain downloaded on my new computer but not sure how to restore the coin. Where can I find some support? When I setup the account it used 2FA there was no key, the wallet is asking for a 24 Word key when I set this up it did not have a 24 word key. If I insert my passphrase it says Mnemonic Decode failed. Unknown language. I have the dat file from the wallet but again how to grab it? Then open that file with a password. I'm updating with the error message below. I simply cannot get this to run on Windows 10 Pro. I have backups of the wallet dat file but what good are they if you can't restore them? And there is no 24 word key. I have printouts of all my keys and when I bought this coin I used a long passphrase that I set.

**Comment by jhmblvd** [comment]
![vtrerror](https://user-images.githubusercontent.com/4975277/39677350-61dfbdc4-512e-11e8-9915-8b17298f6a9f.PNG)

**Comment by vtorrent** [comment]
Dear jhmblvd,

Thank you for your feedback.

Windows 10 v1803 compatibility have been added to the release page

(vTorrent_RC4_0821-Win_1803.zip)

Regards,
vTorrent
