### ISSUE TITLE
Restoring Wallet 

### ISSUE THREAD

**Issue by jhmblvd** [vtorrent/vTorrent-Client#14]
My wallet would not work when I tried updating to newer version. On Windows 10 Pro. Cannot get it to even open up just get an error Application Failed to Start because it could not load the QT platform. I tried installing again, same result. I went to a Windows 7 box and got the app running but when I try to restore my wallet it asks for a 24 word seed which was never provided. When I first got this coin I sat up a 24 character seed. That seed is not accepted now. I get an error about mnemonic Decode failing in unknown language. I have a backup of the wallet dat file but don't know how to grab it. My phone dies and instead of a key I used 2FA. Now, I have a new phone but not the old VTR key. Can someone please help?

**Comment by vtorrent** [comment]
Dear jhmblvd,

Thank you for your feedback.

Windows 10 v1803 compatibility have been added to the release page

(vTorrent_RC4_0821-Win_1803.zip)

Regards,
vTorrent

**Comment by jhmblvd** [comment]
Sorry had a surgery and was away for a week. I am not sure what you are saying here. The release you mention is what I downloaded to begin with. It does not work on Windows 10 PRO. Worked on Windows 10 Home but not Pro. I cannot open the wallet.
