### ISSUE TITLE
Wallet does not open after latest windows update.

### ISSUE THREAD

**Issue by lello1231** [vtorrent/vTorrent-Client#15]
hello,
after updating windows 10 to version 1803 , i am not able to  open my wallet nor reinstalling it, i receive the following error "this application failed to start because it could not find or load the Qt platform plugin "windows" in "". Reinstalling the application may fix the problem. I tried with version . i tried 0.8.1.1 and 0.8.2.1.
Please help,

**Comment by vtorrent** [comment]
Dear Lello,

Thank you for your feedback.

Windows 10 v1803 compatibility have been added to the release page

(vTorrent_RC4_0821-Win_1803.zip)

Regards,
vTorrent

**Comment by jhmblvd** [comment]
I get the same error 
![vtrerror](https://user-images.githubusercontent.com/4975277/40314756-557d2098-5cce-11e8-991d-08b9e792bc42.PNG)
