### ISSUE TITLE
[Windows] The binary inside the zip for the windows system will not open

### ISSUE THREAD

**Issue by evertonstz** [vtorrent/vTorrent-Client#9]
After trying to open the windows client I'm stopped with the following dialog error:

> this application failed to start because it could not find or load the qt platform plugin "windows" in "". Reinstalling the application may fix this problem

File is: vTorrent_RC4_0821-Win.zip

**Comment by taciho** [comment]
https://www.reddit.com/r/vTorrentCrypto/comments/817wy6/how_to_buy_and_where_to_store/dv2bdzn/ maybe this thread helps you. 

Unzip everything before starting the program!
